server:
  port: 9090

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/foodRecipe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root


rabbitmq:
  exchange-auth: exchange-auth
  registerKey: register-mail-key
  registerQueue: register-mail-queue
  forgotPasswordKey: forgot-password-key
  forgotPasswordQueue: forgot-password-queue
