server:
  port: 9075


spring:
  mail:
    username: ${mailUsername}
    password: ${mailPassword}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

rabbitmq:
  registerQueue: register-mail-queue
  forgotPasswordQueue: forgot-password-queue
  notification-mail-queue: notification-mail-queue
