server:
  port: 9070

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: recipe-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: foodRecipesDB
      username: foodUser
      password: root
      auto-index-creation: true

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

