server:
  port: 9080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: foodRecipesDB
      username: foodUser
      password: root
      auto-index-creation: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: userprofile-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}


rabbitmq:
  exchange-user: exchange-user
  notification-mail-key: notification-mail-key
  notification-mail-queue: notification-mail-queue
